apiVersion: v2
name: spark
description: Spark Operator and jobs for streaming
type: application
version: 0.1.0
appVersion: "3.5.0"

dependencies:
  - name: spark-operator
    version: 1.1.27
    repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
