# helm/minio/values.yaml

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2025-09-07T16-13-09Z
  pullPolicy: IfNotPresent

replicas: 1

ports:
  api: 9000
  console: 9001

auth:
  rootUser: minio
  rootPassword: minio123

# Default buckets
defaultBuckets:
  - iceberg
  - warehouse

persistence:
  enabled: true
  size: 5Gi
  storageClass: standard

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

consoleIngress:
  enabled: false
